$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

name: machine_learning_E2E  # Provide the name for the environment
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: ../../../data-science/environment/train-conda.yml
description: Environment created from a Docker image plus Conda environment. # Provide the name for the environment
